name: build

on: [ push, pull_request ]

jobs:
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '12'
      - name: Install packages
        run: npm install
      - name: build
        run: npm run build
